coolsite/coolsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from coolsite import settings
from shop.views import *
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coolsite/shop/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

from .views import *

urlpatterns = [
    path('', ShopMain.as_view(), name='home'),
    path('product/<slug:product_slug>/', ShowProduct.as_view(), name='product'),
    path('category/<slug:cat_slug>/', ProductCategory.as_view(), name='category'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
    path('login/', LoginUser.as_view(), name='login'),
    path('profile/<int:profile_id>/', Profile.as_view(), name='profile'),
    path('product/<slug:product_slug>/<int:product_id>/purchase', purchase, name='purchase'),
    path('history/', PurchasesHistory.as_view(), name='history'),
    path('addproduct/', AddProduct.as_view(), name='addproduct'),
]

coolsite/shop/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_extensions.db.fields import AutoSlugField
import string
import random

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='owner', verbose_name='Добавил')
    description = models.TextField(verbose_name="Описание")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name="Категория")
    count = models.IntegerField(verbose_name="Количество")
    city = models.ForeignKey('City', on_delete=models.PROTECT, verbose_name="Город")
    price = models.IntegerField(verbose_name="Цена")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(default=True, verbose_name="Публикация")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product', kwargs={'product_slug': self.slug})

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото")
    city = models.ForeignKey('City', on_delete=models.PROTECT, verbose_name="Город", default=1)
    balance = models.IntegerField(verbose_name="Баланс", default=0)

    def get_absolute_url(self):
        return reverse('profile', kwargs={'profile_id': self.pk})

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class City(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Город")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.name


class Purchases(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='купил', verbose_name='купил')
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name="Товар")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время покупки")

coolsite/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from shop.models import Product


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class AddProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['owner'].disabled = True
        self.fields['cat'].empty_label = "Категория не выбрана"

    class Meta:
        model = Product
        fields = ['name', 'owner', 'photo', 'description', 'cat', 'count', 'city', 'price', 'is_published', 'slug']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-input'}),
            'description': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
            'owner': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_title(self):
        title = self.cleaned_data['name']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')

        return title

coolsite/shop/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.db.models import Q, F
from django.http import HttpResponse, HttpResponseNotFound, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RegisterUserForm, LoginUserForm, AddProductForm
from .models import *
from .utils import DataMixin


class ShopMain(DataMixin, ListView):
    model = Product
    template_name = 'shop/index.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):  #для передачи динамических данных
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная траница')        #in utils.py  DataMixin
        context.update(c_def)
        return context

    def get_queryset(self):
        return Product.objects.filter(is_published=True)

class ShowProduct(DataMixin, DetailView):
    model = Product
    template_name = 'shop/product.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):  #для передачи динамических данных
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(name=context['product'])        #in utils.py  DataMixin
        context.update(c_def)
        return context

class ProductCategory(DataMixin, ListView):
    model = Product
    template_name = 'shop/index.html'
    context_object_name = 'products'
    parent_id = 0
    #allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):  #для передачи динамических данных
        context = super().get_context_data(**kwargs)
        c = Category.objects.get(slug=self.kwargs['cat_slug'])
        c_def = self.get_user_context(title='Категория - ' + str(c.name),
                                      cat_selected=c.pk)        #in utils.py  DataMixin
        context.update(c_def)
        return context

    def get_queryset(self, object_list=None, **kwargs):
        c = Category.objects.get(slug=self.kwargs['cat_slug'])
        if c.parent_category is None:
            return Product.objects.filter(Q(cat__parent_category=c.pk) | (Q(pk=c.pk)))
        else:
            return Product.objects.filter(cat__slug=self.kwargs['cat_slug'])


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm                           #in forms.py
    template_name = 'shop/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация')
        context.update(c_def)
        return context

def logout_user(request):
    logout(request)
    return redirect('home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'shop/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизация')
        context.update(c_def)
        return context

    def get_success_url(self):
        return reverse_lazy('home')


class Profile(DataMixin, DetailView):
    model = Profile
    template_name = 'shop/profile.html'
    pk_url_kwarg = 'profile_id'
    context_object_name = 'profile'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Профиль - ' + str(self.request.user))
        context.update(c_def)
        return context

def purchase(request, product_id, product_slug):
    p = Purchases(user_id=request.user.id, product_id=product_id)
    p.save()
    Product.objects.filter(pk=product_id).update(count=F('count') - 1)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class PurchasesHistory(DataMixin, ListView):
    model = Purchases
    template_name = 'shop/purchase_history.html'
    context_object_name = 'purchases'

    def get_context_data(self, *, object_list=None, **kwargs):  #для передачи динамических данных
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='История покупок')
        context.update(c_def)
        return context

    def get_queryset(self):
        return Purchases.objects.filter(user=self.request.user.id)

class AddProduct(LoginRequiredMixin, DataMixin, CreateView):                                 # @login_required если функции представления
    form_class = AddProductForm
    template_name = 'shop/addproduct.html'
    success_url = reverse_lazy('home')
    login_url = reverse_lazy('home')
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):  #для передачи динамических данных
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавление объявление')
        context.update(c_def)
        return context

    def get_initial(self):
        return {'owner': self.request.user.id}

coolsite/shop/templates/shop/addproduct.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form action="{% url 'addproduct' %}" method="post" enctype="multipart/form-data">  <!-- enctype в случае передачи файлов совместно с даннымы в форме -->
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Добавить</button>
</form>


{% endblock %}

coolsite/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'shop/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="#"><div class="logo"></div></a></li>
{% for m in menu %}
			<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
				{% if request.user.is_authenticated %}
				<li class="last"> <a href="{{ user.profile.get_absolute_url }}">{{user.username}} </a> | <a href="{% url 'logout' %}">Выйти</a></li>
					<li class="last">{{user.profile.balance}} $</li>
				{% else %}
				<li class="last"> <a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a></li>
				{% endif %}

			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
{% else %}
		<li><a href="{% url 'home' %}">Все категории</a></li>
{% endif %}

{% for c in cats %}
	{% if c.pk == cat_selected %}
		<li class="selected">{{c.name}}</li>
		{% for subcat in subcats %}
			<li style="margin-left: 25px;"><a href="{{ subcat.get_absolute_url }}">   >{{subcat.name}}</a></li>
		{% endfor %}
	{% else %}
		<li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
	{% endif %}
{% endfor %}

<!--{% for category in categories %}-->
<!--    {% for subcategory in category.category_set.all %}-->
<!--        {{ subcategory }}-->
<!--    {% endfor %}-->
<!--{% endfor %}-->

		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

coolsite/shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in products %}
			<li><div class="article-panel">
	<p class="first">Категория: {{p.cat}}</p>
	<p class="last" style="margin-left: 50px;">Дата: {{p.time_create|date:"d-m-Y H:i:s"}}</p>
	<p class="last" style="margin-left: 50px;">Цена: {{p.price}} грн </p>
</div>

{% if p.photo %}
	<p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
{% endif %}

				<h2>{{p.name}}</h2>
	{% autoescape on %}
	{{p.description|linebreaks|truncatewords:50}}
	{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Просмотреть объявление</a></p>
			</li>
	{% endfor %}
</ul>
{% endblock %}

coolsite/shop/templates/shop/login.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

<div class="form-error">{{ form.non_fields_errors }}</div>
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Войти</button>
</form>

{% endblock %}

coolsite/shop/templates/shop/product.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>{{product.name}}</h1>

{% if product.photo %}
<p><img class="img-article-left" src="{{product.photo.url}}"></p>
{% endif %}

{{product.description|linebreaks}}
  <li style="margin-left: 25px;">Город: {{ product.city }}</li>
  <li style="margin-left: 25px;">Количество: {{ product.count }}</li>
  <li style="margin-left: 25px;">Продавец: {{ product.owner_id }}</li>
  <li style="font-weight:bold;">Цена: {{ product.price }}</li>

{% if product.count > 0 %}
<form action="{{product.id}}/purchase" method="post">
{% csrf_token %}
<input type="submit" class="purchase" value="Купить" name="purchase">
</form>
{% else %}
<li style="font-weight:bold;">Товара нет в наличии</li>
{% endif %}
{% endblock %}

coolsite/shop/templates/shop/profile.html
{% extends 'shop/base.html' %}
<title>{{user.username}}</title>
{% block content %}

<h1>{{user.username}}</h1>

{% if user.profile.photo %}
<p><img class="img-article-left" src="{{user.profile.photo.url}}"></p>
{% endif %}
  <li style="margin-left: 25px;">Имя: {{ user.first_name }}</li>
  <li style="margin-left: 25px;">Фамилия: {{ user.second_name }}</li>
  <li style="margin-left: 25px;">Регистрация: {{ user.date_joined }}</li>
  <li style="margin-left: 25px;">Имя пользователя: {{ user.username }}</li>
  <li style="margin-left: 25px;">Местоположение: {{ user.profile.city }}</li>
  <li style="margin-left: 25px;">Баланс: {{ user.profile.balance }}</li>

{{profile.bio|linebreaks}}
<!--<h1>Цена: {{product.price}} </h1>-->

{% endblock %}

coolsite/shop/templates/shop/purchase_history.html
{% extends 'shop/base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in purchases %}
			<li><div class="article-panel">
	<p class="last" style="margin-left: 50px;">Цена: {{p.product.price}} </p>
	<p class="last" style="margin-left: 50px;">Дата покупки: {{p.time_update}} </p>
</div>

{% if p.product.photo %}
	<p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
{% endif %}

				<h2>{{p.product.name}}</h2>
	{% autoescape on %}
	{{p.description|linebreaks|truncatewords:50}}
	{% endautoescape %}
			<div class="clear"></div>
			</li>
	{% endfor %}
</ul>
{% endblock %}

coolsite/shop/templates/shop/register.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}
    <button type="submit">Регистрация</button>
</form>

{% endblock %}